name: auto_inject
description: Provides annotations for the auto inject code generation.
version: 0.0.1
homepage: https://github.com/LeFrosch/auto-inject

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  get_it: ">=7.0.0 <8.0.0"

dev_dependencies: 
  lints: ^1.0.1
