name: auto_inject_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies: 
  analyzer: ^2.3.0
  build: ^2.1.0
  code_builder: ^4.1.0
  source_gen: ^1.1.1
  glob: ^2.0.1
  
  auto_inject: 
    path: ../auto_inject

dev_dependencies:
  build_runner: ^2.1.2
  test: ^1.17.12

