name: auto_inject_generator
description: Code generation for get it.
version: '0.0.3'
homepage: https://github.com/LeFrosch/auto-inject

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'


dependencies: 
  analyzer: ^2.3.0
  build: ^2.1.0
  code_builder: ^4.1.0
  source_gen: ^1.1.1
  glob: ^2.0.1
  
  auto_inject: 
  #  git:
  #    url: https://github.com/LeFrosch/auto-inject.git
  #    path: auto_inject
    path: ../auto_inject

dev_dependencies:
  build_runner: ^2.1.2
  lints: ^1.0.1
  test: ^1.17.12

